hrms_core/Controllers/AssociateController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using hrms_core.Models;
using hrms_core.ViewModel;
using hrms_core.EF;
using hrms_core.ViewModel.Services.Interfaces;
using hrms_core.ViewModel.Services;
using System.Transactions;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace hrms_core.Controllers
{
    public class AssociateController : Controller
    {
        private readonly ApplicationDbContext _db;
        public IConfiguration Configuration { get; }
        private IAssociateServices associateServices => new AssociateServices(_db);
        private IDesignationServices designationServices => new DesignationServices(_db);
        private IDepartmentServices departmentServices => new departmentServices(_db);
        private IQualificationServices qualificationServices => new QualificationServices(_db);
        private ICountryServices countryServices => new CountryServices(_db);
        private IStateServices stateServices => new StateServices(_db);
        private ICityServices cityServices => new CityServices(_db);
        private IRoleServices roleServices => new RoleServices(_db);

        public AssociateController(ApplicationDbContext db, IConfiguration configuration)
        {
            _db = db;
            Configuration = configuration;
        }

        public IActionResult AssociateBucket()
        {
            SessionModel SesMdl = HttpContext.Session.GetObjectFromJson<SessionModel>(SessionVariables.SessionData);
            if (SesMdl == null)
            {
                return RedirectToAction("Login", "Account");
            }
            AssociateVM associate = new AssociateVM();
            associate.createdby = SesMdl.associate_id;
            associate.createdbyname = SesMdl.associate_name;
            associate.updatedby = SesMdl.associate_id;
            associate.updatedbyname = SesMdl.associate_name;
            associate.AssociateVMList = (from master in _db.AssociateMasters.Where(x => x.isactive == true && x.is_super_admin == false)
                                         join main in _db.AssociateMains
                                         on master.id equals main.associate_id
                                         select new AssociateVM
                                         {
                                             associate_id = master.id,
                                             associate_code = master.associate_code,
                                             associate_name = master.associate_name,
                                             designation = _db.Designations.FirstOrDefault(x => x.id == main.designation_id).designationtext,
                                             department = _db.Departments.FirstOrDefault(x => x.id == main.department_id).departmenttext,

                                             contact = main.mobileno,
                                             DOJ = master.application_date,
                                         }).ToList();

            associate.AssociateVMInactiveList = (from master in _db.AssociateMasters.Where(x => x.isactive == false && x.is_super_admin == false)
                                                 join main in _db.AssociateMains
                                                 on master.id equals main.associate_id
                                                 select new AssociateVM
                                                 {
                                                     associate_id = master.id,
                                                     associate_code = master.associate_code,
                                                     associate_name = master.associate_name,
                                                     designation = _db.Designations.FirstOrDefault(x => x.id == main.designation_id).designationtext,
                                                     department = _db.Departments.FirstOrDefault(x => x.id == main.department_id).departmenttext,
                                                     contact = main.mobileno,
                                                     DOJ = master.application_date,
                                                 }).ToList();
            return View(associate);
        }
        [HttpGet]
        public IActionResult Index(int? id, int? view)
        {
            AssociateVM model = new AssociateVM();
            SessionModel SesMdl = HttpContext.Session.GetObjectFromJson<SessionModel>(SessionVariables.SessionData);
            if (SesMdl != null)
            {
                if (view == 1)
                {
                    model.view = 1;
                }
                else
                {
                    model.view = 0;
                }
                model.createdby = SesMdl.user_id;
                model.updatedby = SesMdl.user_id;
                model.createdbyname = SesMdl.username;
                model.updatedbyname = SesMdl.username;
                model.associateMaster.application_date = DateTime.Now.Date;
                #region Bind Designation Dropdown
                model.DesignationModelList = designationServices.GetDesignation_Active();
                model.DesignationModelList.Insert(0, new DesignationModel { id = 0, designationtext = "--Select--" });
                #endregion

                #region Bind Department Dropdown
                model.DepartmentModelList = departmentServices.GetDepartment_Active();
                model.DepartmentModelList.Insert(0, new DepartmentModel { id = 0, departmenttext = "--Select--" });
                #endregion

                #region Bind Reporting_Person(Associate) Dropdown
                model.associateMaster.AssociateMasterModelList = associateServices.GetAssociateList_Active();
                model.associateMaster.AssociateMasterModelList.Insert(0, new AssociateMasterModel { id = 0, associate_name = "--Select--" });
                #endregion

                #region Bind Qualification Dropdown
                model.qualificationModel.QualificationModelList = qualificationServices.GetQualification_Active();
                model.qualificationModel.QualificationModelList.Insert(0, new QualificationModel { id = 0, qualificationtext = "--Select--" });
                #endregion
                #region Bind Country Dropdown
                model.PresentCountryModelList = countryServices.GetCountry_Active();
                model.PermanentCountryModelList = countryServices.GetCountry_Active();
                model.PresentCountryModelList.Insert(0, new CountryModel { id = 0, countrytext = "--Select--" });
                 model.PermanentCountryModelList.Insert(0, new CountryModel { id = 0, countrytext = "--Select--" });
                #endregion

                #region Bind Role DropDown
                model.RoleList = roleServices.GetRoleList();
                model.RoleList.Insert(0, new RoleMasterModel { id = 0, role_name = "--Select--" });
                #endregion
                model.PresentStateModelList.Insert(0, new StateModel { id = 0, statetext = "--Select--" });
                model.PermanentStateModelList.Insert(0, new StateModel { id = 0, statetext = "--Select--" });
                model.PresentCityModelList.Insert(0, new CityModel { id = 0, citytext = "--Select--" });
                model.PermanentCityModelList.Insert(0, new CityModel { id = 0, citytext = "--Select--" });
                if (id != null && id > 0)
                {
                    #region Master
                    model.associateMaster = _db.AssociateMasters.Where(x => x.id == id )
                   .Select(x => new AssociateMasterModel
                   {
                       id = x.id,
                       associate_name = x.associate_name,
                       applicable_to = x.applicable_to,
                       application_date = x.application_date,
                       associate_code = x.associate_code,
                       createdby = x.createdby,
                       createdon = x.createdon,
                       updatedby = x.updatedby,
                       updatedon = x.updatedon,
                       isactive = x.isactive,
                       AssociateMasterModelList = associateServices.GetAssociateList_Active()
                   }).FirstOrDefault();
                    #endregion
                    #region Main
                    model.associateMain = (from master in _db.AssociateMasters.Where(x => x.id == id )
                                           join main in _db.AssociateMains
                                           on master.id equals main.associate_id
                                           select new AssociateMainModel
                                           {
                                               id = main.id,
                                               associate_id = main.associate_id,
                                               designation_id = main.designation_id,
                                               department_id = main.department_id,
                                               is_hod = main.is_hod,
                                               extensionno = main.extensionno,
                                               mobileno = main.mobileno,
                                               personal_email = main.personal_email,
                                               official_email = main.official_email,
                                               account_no = main.account_no,
                                               bankname = main.bankname,
                                               ifsc = main.ifsc,
                                               doc = (main.doc == null ? default(DateTime) : main.doc),

hrms_core/Views/Associate/AssociateBucket.cshtml
@model hrms_core.Models.AssociateVM
@{
    ViewData["Title"] = "Associate Bucket";
}

<section class="content-header">
    <h1>Associate Details</h1>
</section>
<section class="content">
    <div id="MsgDiv">
        @if (TempData["msg"] != null)
        {
            if (Convert.ToString(TempData["msg"]).ToLower().Contains("wrong") || Convert.ToString(TempData["msg"]).ToLower().Contains("not"))
            {
                <div class='alert alert-danger'>
                    <label>@TempData["msg"]</label><a onclick="$('#MsgDiv').hide(500);" class="anchor pull-right"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                </div>
            }
            else if (Convert.ToString(TempData["msg"]).ToLower().Contains("already") || Convert.ToString(TempData["msg"]).ToLower().Contains("exist"))
            {
                <div class='alert alert-warning'>
                    <label>@TempData["msg"]</label><a onclick="$('#MsgDiv').hide(500);" class="anchor pull-right"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                </div>
            }
            else
            {
                <div class='alert alert-success'>
                    <label>@TempData["msg"]</label><a onclick="$('#MsgDiv').hide(500);" class="anchor pull-right"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                </div>
            }
        }
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#tab_1" data-toggle="tab">Active Employees</a></li>
                    <li><a href="#tab_2" data-toggle="tab">In-Active Employees</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="tab_1">

                        <div class="box box-default">
                            <div class="box-header with-border">
                            </div>
                            <div class="box-body">
                                <div class="callout callout-info nofoundlbl" style="display:none;"></div>
                                <div class="" style="max-height: 400px;min-height: 153px;overflow-y: auto;">
                                    <table id="tblAssociate" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Associate Code</th>
                                                <th>Associate Name</th>
                                                <th>Designation</th>
                                                <th>Department</th>
                                                <th>Contact</th>
                                                <th>DOJ</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{

                                                foreach (var item in Model.AssociateVMList)
                                                {
                                                    <tr>
                                                        <td>@item.associate_code</td>
                                                        <td>@item.associate_name</td>
                                                        <td>@item.designation</td>
                                                        <td>@item.department</td>
                                                        <td>@item.contact</td>
                                                        <td>@item.DOJ.ToString("dd-MM-yyyy")</td>
                                                        <td>
                                                            <a asp-controller="Associate" asp-action="Index" title="view" asp-route-id="@item.associate_id" asp-route-view="1"><i class="fa fa-eye"></i></a>|
                                                            <a asp-controller="Associate" asp-action="Index" title="edit" asp-route-id="@item.associate_id" asp-route-view="2" class="fa fa-pencil"></a>|
                                                            <a asp-controller="Associate" asp-action="DeleteAssociate" title="delete" asp-route-id="@item.associate_id" class=" fa fa-close"></a>
                                                        </td>
                                                    </tr>

                                                }
                                            }
                                        </tbody>
                                    </table>
                                </div>
                                </div>
                            </div>

                    </div>
                    <div class="tab-pane" id="tab_2">

                        <div class="box box-default">
                            <div class="box-header with-border">
                            </div>
                            <div class="box-body">
                                <div class="callout callout-info nofoundlbl" style="display:none;"></div>
                                <div class="" style="max-height: 400px;min-height: 153px;overflow-y: auto;">
                                    <table id="tblInactiveAssociate" class="table table-bordered table-striped">
                                        <thead>
                                            <tr>
                                                <th>Associate Code</th>
                                                <th>Associate Name</th>
                                                <th>Designation</th>
                                                <th>Department</th>
                                                <th>Contact</th>
                                                <th>DOJ</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{

                                                foreach (var item in Model.AssociateVMInactiveList)
                                                {
                                                    <tr>
                                                        <td>@item.associate_code</td>
                                                        <td>@item.associate_name</td>
                                                        <td>@item.designation</td>
                                                        <td>@item.department</td>
                                                        <td>@item.contact</td>
                                                        <td>@item.DOJ</td>
                                                        <td>
                                                            <a asp-controller="Associate" asp-action="Index" asp-route-id="@item.associate_id" title="view" asp-route-view="1"><i class="fa fa-eye"></i></a>|
                                                            <a asp-controller="Associate" asp-action="ActivateAssociate" title="resume" asp-route-id="@item.associate_id" class="fa fa-undo"></a>
                                                        </td>
                                                    </tr>

                                                }
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script>
        $(document).ready(function () {
            $("#tblAssociate").DataTable({
                "lengthMenu": [[100, 50, 20, -1], [100, 50, 20, "All"]],
                "pageLength": 30,
                dom: 'lBfrtip',
                buttons: [
                    'excel', 'pdf', 'print'
                ]
            });
            $('#tblInactiveAssociate').DataTable(
                {
                    "lengthMenu": [[100, 50, 20, -1], [100, 50, 20, "All"]],
                    "pageLength": 30,
                    dom: 'lBfrtip',
                    buttons: [
                        'excel', 'pdf', 'print'
                    ]
                });
        });
    </script>
}

hrms_core/Views/Associate/DownloadExtension.cshtml
@model hrms_core.Models.AssociateVM

@{
    ViewData["Title"] = "Download Associate Extension Codes";
}


<section class="content-header">
    <h1>@ViewData["Title"]</h1>
</section>

<section class="content">
    <link href="~/datatables/dataTables.bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.1/css/buttons.dataTables.min.css" />
    
       <div class="col-md-12">
            <div class="box box-primary">
                
                <div class="box-body">
                  
                    
                    <div class="col-md-12">
                        <div class="box-header with-border">
                            <span>Associate Extension Details</span>
                        </div>
                        <div class="box-body">
                            <table id="tblData" class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>SNo.</th>
                                        <th>Associate Name</th>
                                        <th>Associate Extension</th>
                                        
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        int i = 1;
                                        foreach (var item in Model.AssociateExtension)
                                        {
                                            <tr>
                                                <td>@i</td>
                                                <td>@item.associate_name</td>
                                                <td>@item.extension</td>
                                                
                                            </tr>
                                            i = i + 1;
                                        }

                                    }
                                </tbody>
                            </table>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
 
</section>

@section Scripts{

    <script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#tblData').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'excelHtml5',
                        text: 'Download',

                    }
                ]
            })
        });
    </script>
}