hrms_core/Models/Shift.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace hrms_core.Models
{
    public class Shift:CommonAttributeModel
    {
        [Key]
        public int id { get; set; }
        [Required(ErrorMessage = "Enter Shift Name")]
        public string shifttext { get; set; }
        public DateTime starttime { get; set; }
        public DateTime endtime { get; set; }
        public DateTime totaltime { get; set; }
        public DateTime breaktime { get; set; }
        public DateTime networkingtime { get; set; }
        public string tolerance { get; set; }
        public bool nightshift { get; set; }
    }
}

hrms_core/Controllers/ShiftMasterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using hrms_core.EF;
using hrms_core.ViewModel;
using hrms_core.ViewModel.Services;
using hrms_core.ViewModel.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace hrms_core.Controllers
{
    public class ShiftMasterController : Controller
    {
        private readonly ApplicationDbContext _db;
        private IShiftServices shiftServices => new ShiftServices(_db);
        public ShiftMasterController(ApplicationDbContext options) => _db = options;


        [HttpGet]
        public IActionResult Shift()
        {
            // TODO : Check the Accessbility and do the needful
            return View();
        }
    }
}

hrms_core/Views/ShiftMaster/Shift.cshtml
@model hrms_core.ViewModel.ShiftModel

@{
    ViewData["Title"] = "Shift";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Shift Master
    </h1>
</section>
<!-- Main content -->
<section class="content">
    <div class="row">

        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Shift Details</h3>
            </div>
            <div class="box-body">
                <div id="msgdiv"></div>
                <div class="form-group col-md-6">
                    <label><span style="color: #ff0000;">*</span> Name</label>
                    <input type="text" class="form-control CharcaterTextBox" id="shift_name"
                           maxlength="50" placeholder="Enter Shift Name" onfocus="RemoveValidation(this);" required>
                </div>
                <div class="form-group col-md-6">
                    <label> Night Shift</label>
                    <input type="checkbox" id="night_shift" value="FALSE" class="night" style="margin-top:32px;" />
                </div>
                <div class="form-group col-md-6">
                    <div class="bootstrap-timepicker">
                        <label><span style="color: #ff0000;">*</span> Start Time</label>
                        <input type="text" class="form-control NumericTextBox" id="start_time"
                               maxlength="100" placeholder="00:00" onfocus="RemoveValidation(this);" required>
                    </div>
                </div>
                <div class="form-group col-md-6">
                    <label><span style="color: #ff0000;">*</span> End Time</label>
                    <input type="text" class="form-control NumericTextBox" id="end_time"
                           maxlength="100" placeholder="00:00" onfocus="RemoveValidation(this);" required>
                </div>
                <div class="form-group col-md-6">
                    <label> Total Time</label>
                    <input type="text" class="form-control" id="total_time"
                           maxlength="100" placeholder="00:00" readonly="readonly" required>
                </div>
                <div class="form-group col-md-6">
                    <label> Break Time</label>
                    <select id="break_time" class="form-control">
                        <option>Select</option>
                        <option value="00:05:00">5 mnt</option>
                        <option value="00:10:00">10 mnt</option>
                        <option value="00:15:00">15 mnt</option>
                        <option value="00:20:00">20 mnt</option>
                        <option value="00:25:00">25 mnt</option>
                        <option value="00:30:00">30 mnt</option>
                        <option value="00:35:00">35 mnt</option>
                        <option value="00:40:00">40 mnt</option>
                        <option value="00:45:00">45 mnt</option>
                        <option value="00:50:00">50 mnt</option>
                        <option value="00:55:00">55 mnt</option>
                        <option value="01:00:00">1 hr</option>
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label> Net Working Time</label>
                    <input type="text" class="form-control" id="net_working_time"
                           maxlength="100" placeholder="00:00" readonly="readonly" required>
                </div>
                <div class="form-group col-md-6">
                    <label> Tolerance(Minutes)</label>
                    <input type="text" class="form-control NumericTextBox" id="tolerance"
                           maxlength="100" placeholder="" required>
                </div>
                <!-- /.box-body -->
            </div>
            <div class="box-footer">
                <button class="btn btn-primary" id="addshift_master_btn">Save</button>
                <button class="btn btn-primary" id="shift_back_btn">Back</button>
            </div>
            <!-- /.box-body -->
            <!-- /.box -->
        </div>
    </div>

    <div class="col-md-7">
        <div class="box box-default">
            <div class="box-header with-border">
                <h3 class="box-title">Shift Master List</h3>
            </div>
            <div class="box-body">
                <table id="tblShiftMaster" class="table table-striped">
                    <thead>
                        <tr>
                            <th>S.No.</th>
                            <th>Shift Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>


                        @{
                            int i = 1;
                            foreach (var item in Model.ShiftModelList)
                            {
                                <tr>
                                    <td>@i</td>
                                    <td>@item.shifttext</td>

                                    <td>
                                        <a title="Edit" href="@Url.Action("Shift","ShiftMaster",new { id=item.id})"><i class="fa fa-edit"></i></a> |
                                        @{
                                            if (item.isactive.HasValue == true && item.isactive.Value == true)
                                            {
                                                <a class="anchor" onclick="DisableData(@item.id)" title="Click to Disable"><img src="~/images/green.ico" alt="Enable" height="18" width="18" /></a>
                                            }
                                            else
                                            {
                                                <a class="anchor" onclick="EnableData(@item.id)" title="Click to Enable"><img src="~/images/red.ico" alt="Disable" height="18" width="18" /></a>
                                            }
                                        }
                                    </td>
                                </tr>
                                i = i + 1;
                            }
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</section>
<!-- /.content -->