hrms_core/Models/ConferenceRoom.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace hrms_core.Models
{
    public class ConferenceRoom : CommonAttributeModel
    {
        [Key]
        public int even_id { get; set; }
        [ForeignKey("associate_id")]
        public int associate_id { get; set; }
        [Required(ErrorMessage ="Event Subject is required")]
        public string subject { get; set; }
        public string description { get; set; }
        [Required(ErrorMessage ="Starting date is required")]
        public DateTime startsession { get; set; }
        [Required(ErrorMessage = "Start time is required")]
        public TimeSpan starttime { get; set; }
        [Required(ErrorMessage ="End time is required")]
        public TimeSpan endtime { get; set; }
        public string themecolor { get; set; }
        public bool isfullday { get; set; }
    }
}

hrms_core/Controllers/ConferenceRoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using hrms_core.ViewModel;
using hrms_core.EF;

namespace hrms_core.Controllers
{
    public class ConferenceRoomController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ConferenceRoomController(ApplicationDbContext _Db)
        {
            _db = _Db;
        }
        [HttpGet]
        public IActionResult Index(int? id)
        {
            ConferenceRoomModel model = new ConferenceRoomModel();
            //model.conferenceEvents=
            return View(model);
        }
    }
}

hrms_core/Views/ConferenceRoom/Index.cshtml
@model hrms_core.ViewModel.ConferenceRoomModel
@{
    ViewData["Title"] = "Index";
}

<section class="content-header">
    <h1>
        Project Master
    </h1>
</section>
<section class="content">
    <div id="MsgDiv">
        @if (TempData["msg"] != null)
        {
            if (Convert.ToString(TempData["msg"]).ToLower().Contains("wrong") || Convert.ToString(TempData["msg"]).ToLower().Contains("not"))
            {
                <div class='alert alert-danger'>
                    <label>@TempData["msg"]</label><a onclick="$('#MsgDiv').hide(500);" class="anchor pull-right"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                </div>
            }
            else if (Convert.ToString(TempData["msg"]).ToLower().Contains("already") || Convert.ToString(TempData["msg"]).ToLower().Contains("exist"))
            {
                <div class='alert alert-warning'>
                    <label>@TempData["msg"]</label><a onclick="$('#MsgDiv').hide(500);" class="anchor pull-right"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                </div>
            }
            else
            {
                <div class='alert alert-success'>
                    <label>@TempData["msg"]</label><a onclick="$('#MsgDiv').hide(500);" class="anchor pull-right"><i class="fa fa-window-close" aria-hidden="true"></i></a>
                </div>
            }
        }
    </div>

    <div class="col-md-12">
        <div class="col-md-4">
            <form asp-controller="ConferenceRoom" asp-action="Index" method="post">
                <div class="box box-default">
                    <div class="box-header with-border">
                        <h3 class="box-title">Conference Room Events</h3>
                    </div>
                    <div class="box-body">
                        <div class="form-group col-md-12">
                            <label><span style="color: #ff0000;">*</span> Event Subject</label>
                            <input type="text" class="form-control" id="Subject" maxlength="50" placeholder="Enter Event Subjecrt" asp-for="subject" />
                            <span asp-validation-for="subject" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label><span style="color: #ff0000;">*</span> Event Description</label>
                            <input type="text" class="form-control" id="Description" maxlength="50" placeholder="Enter Event Subjecrt" asp-for="description" />
                            <span asp-validation-for="description" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label><span style="color: #ff0000;">*</span> Start Date</label>
                            <input class="form-control" type="date" asp-format="{0:yyyy-MM-dd}" id="start_date" maxlength="50" asp-for="startsession" />
                            <span asp-validation-for="startsession" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label><span style="color: #ff0000;">*</span> Start Time</label>
                            <input type="time" class="form-control" placeholder="hh-mm-ss" id="start_time" maxlength="50" asp-for="starttime" />
                            <span asp-validation-for="starttime" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <label><span style="color: #ff0000;">*</span> End Time</label>
                            <input type="time" class="form-control" placeholder="hh-mm-ss" id="end_time" maxlength="50" asp-for="endtime" />
                            <span asp-validation-for="endtime" class="text-danger"></span>
                        </div>
                        <div class="form-group col-md-12">
                            <div class="form-group col-md-6">
                                <label>Theme Color</label>
                                <input type="color" class="form-control" id="theme color" maxlength="50" asp-for="themecolor" />
                                <span asp-validation-for="themecolor" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label>IsFullDay</label>
                                <input type="checkbox" class="checkbox" asp-for="isfullday" />
                            </div>
                        </div>
                        </div>
                    <div class="box-footer">
                        <input type="submit" class="btn btn-primary btn-flat" value="Save Changes" id="btnSave" />
                        <a asp-action="Index" asp-controller="ConferenceRoom" asp-route-id="" class="btn btn-danger btn-flat">Clear</a>
                    </div>
                </div>
            </form>
        </div>
        


            <div class="col-md-8">
                <div class="box box-default">
                    <div class="box-header with-border">
                        <h3 class="box-title">Current Leave Status</h3>
                    </div>
                    <div class="box-body">
                        <div class="callout callout-info nofoundlbl" style="display:none;"></div>
                        <div class="" style="max-height: 153px;min-height: 153px;overflow-y: auto;">
                            <table id="tblEvenname" class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th>Event Subject</th>
                                        <th>Event Description</th>
                                        <th>Date</th>
                                        <th>Start Time</th>
                                        <th>End Time</th>
                                        <th>Theme Color</th>
                                        <th>IsFullDay</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{

                                        int i = 1;
                                        foreach (var item in Model.conferenceEvents)
                                        {
                                                <tr class='alert alert-danger'>
                                                    <td>@i</td>
                                                    <td>@item.subject</td>
                                                    <td>@item.description</td>
                                                    <td>@item.startsession</td>
                                                    <td>@item.starttime</td>
                                                    <td>@item.endtime</td>
                                                    <td>@item.themecolor</td>
                                                    <td>@item.isfullday</td>
                                                </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>